### ISSUE TITLE
Error on installing plugin!

### ISSUE THREAD

**Issue by hhhhwwww** [Mibew/geo-ip-plugin#1]
pluging state ERROR: "Not initialized".

**Comment by JustBlackBird** [comment]
Then you do something wrong. The plugin works fine in our demo installation.

**Comment by hhhhwwww** [comment]
Hi, you can see on many users they post pluging state ERROR: "Not initialized".
And many answer from "supporters" like this:
"Then you do something wrong. The plugin works fine in our demo installation."

But it is not solution for us. I'll go now to uninstall this crap because doesn't work and don't have support!
I am sure then I will done a  "**SOMETHING RIGHT**!"

**Comment by JustBlackBird** [comment]
I have no telepathic abilities to get what exactly you do.

Mibew (and its plugin) is an opensource software. We don't _have_ to provide any support at all. All supporters are volunteers who get no money for their job.

If you don't like Mibew you can either don't use it or help us to improve it. If you choose the first option, go on uninstall it. Personally I will not regret about your leaving because you do nothing for the project.

And please, keep all you rage for yourself. It's not helpful in any case.

**Comment by JustBlackBird** [comment]
By the way, the issue is closed because I cannot reproduce your problem. Only if you describe what exactly you're doing I could help you.

**Comment by hhhhwwww** [comment]
That is not my problem but problem of thousand of users.
Just search around for phrase "Mibew not initialized".
And replies for it is like reply from 15years old's.

**Comment by JustBlackBird** [comment]
Yeah, I don't think plugins system in Mibew is perfect. And it definitely need to be improved. **But** personally I have no free time to do it. Also I don't see any Pull Requests with such enhancements.

Once again, Mibew is an opensource software. If you think that something is badly wrong with it you can either do not use it or help us to improve it. There are no other ways.

One more thing, GitHub issue tracker is not a place for pointless talks ;)

**Comment by hhhhwwww** [comment]
How to improve something when you stop all communications about it?
This is an issue so I recommend to leave this open, maybe come here someone who will found why is this happen and together we will find where is a problem and IMPROVE IT.
Closing/stopping communications will not help at all. Specially if you don't think plugins system in Mibew is not perfect, as you write.

**Comment by JustBlackBird** [comment]
Rage made you blind. I've told you:

> Only if you describe what exactly you're doing I could help you.

There are still no details about the problem described by you.

This issue is locked now to stop the pointless chat. Please, open new issue with **all the details** about the problem if you really want your problem to be solved.
