### ISSUE TITLE
Error on installing plugin!

### ISSUE THREAD

**Issue by hhhhwwww** [Mibew/geo-ip-plugin#2]
Error on installing plugin! State says "not initialized"
That is not my problem but problem of thousand of users.
Just search around for phrase "Mibew not initialized".
And replies for it is like reply from 15years old's.

**Comment by hhhhwwww** [comment]
"Please, open new issue with all the details about the problem if you really want your problem to be solved."
- can I ask what "**all the details**" means ? Apache ver., Db ver., PHP ver. and what else ??

**Comment by JustBlackBird** [comment]
What exactly you do before get the error. Most likely the problem in wrong files path, but I have no telepathic abilities to say for sure.

**Comment by hhhhwwww** [comment]
I exactly do what is written in installation steps.
There are nothing about files path so I don't touching nothing else and my Mibew works nice.
Just plugin have problem because is says on state: "not initialized". And that's not only me.

**Comment by JustBlackBird** [comment]
I'll try for the last time.

Where exactly do you put plugin's files? What's in error log?

**Comment by hhhhwwww** [comment]
I put my plugins in my plugin folder.
I unzipped it and it was extracted.
Then I see I have to edit my conf file, so I edited it too. (config.yml).
I see the plugin in my plugin section and there is options enable and uninstall.
As it says in installation process, I have then clicked enable, and it says on state: "not initialized".

**Comment by JustBlackBird** [comment]
Please, provide exact files structure

**Comment by hhhhwwww** [comment]
files structure of the plugin ?
plugins/AARInnovations/Mibew/Plugin/TrayNotification

**Comment by JustBlackBird** [comment]
It's another plugin! You've used wrong repository to file an issue.

**Comment by hhhhwwww** [comment]
So what? Another plugin but still not works as not works your plugin, same shit just different repository.

**Comment by JustBlackBird** [comment]
I'm not the a maintainer of that plugin. So I cannot help you.

Please do not open issues that are not related with `Mibew:GeoIp` plugin here.

**Comment by JustBlackBird** [comment]
Duplicate of #1. Both are not related with `Mibew:GeoIp` plugin.
